include::_partials/README.adoc[tag=metadata]
= Governance of municipal data: the Municipal Data Office

This *Strategy for the responsible and ethical use of data* entails an organisational change that should enable the proper application of the provisions that include it.

== Organisation: the Municipal Data Office

The *Municipal Data Office* (MDO) has been created.
This is a directorate made up of various other directorates and departments that, until now, have had missions concerning council data The Municipal Data Office is located in the Municipal Manager’s Office and answers to the Commission for Technology and Digital Information (CTID).

The MDO is responsible for the management, quality, governance and exploitation of data relating to Barcelona City Council and all its associated bodies (public and private) that provide services to the general public.
The director of the DMO. the Chief Data Officer, (*CDO*) carries out this task by means of:

* The promotion, execution and supervision of data exploitation projects needed by City Council departments.
Relevant city players from the data sector are also involved.
In order to carry out this task, there is an office for multi-disciplinary support.

* The establishment of standardised protocols throughout the organisation and a precise mapping of all the existing wealth of data under the umbrella of the City Council, creating a classification for all the data and the promotion of appropriate processing, care and preservation policies for each one.

* Furthermore, their office will oversee responsible data management, in accordance with current legislation concerning privacy, through coordination with the data protection officer (DPO) and will supervise the integration of the data generated by new contracts and services into the municipal structure.

* Management and monitoring of council-data governance.

The Municipal Data Office is an opportunity to stand out in the field of data, at municipal, community, national and European levels, and this is happening at a good time.
This is obviously a venture for the future and the present, as data is inundating each and every area of our lives, and in the near future, every municipal service will be likely to generate data.
This means that, as an organisation, we have to be prepared and have a solid strategy for how to manage this data and, where necessary, exploit it in order to improve the services provided for the general public.
Due to the nature of its activities, the Office must have an inter-disciplinary, coherent team.
Normally, the required profiles (from the Office or through contact with other City Council units) would be administrative (data governance, specifications), legal (privacy and licence aspects) technical in various disciplines (knowledge of existing data architecture and the actions needed during their life cycle in order to turn them into an asset, as well as technical procedures for ensuring the FAIR use of the data), analytic (one of the Office’s latest objectives is to carry out data science), graphic (there will be a constant need for communicating knowledge extracted from the data through visual means) and finally, a business perspective (the Office will have to provide services to various City Council units).

Furthermore, another Office objective will be promoting the management of change, with the aim of transforming the organisation’s culture, promoting the standardisation of data-management protocols and encouraging the various municipal players to share data and receive training in this area.
This requires decisive political support, which will provide the new office with resources and the authority to carry out the ambitious tasks it is charged with.

Beyond political support, in order to achieve this end, the Office or the CDO must be considered as a service provider by the other City Council units.
This means that the Office must provide useful information and work side by side with the other units, in order to educate them in data culture and encourage them to continue on their own once the collaboration comes to an end.
For this reason, it has to be situated in an appropriate location and with suitable offices.

The MDO’s main functions and responsibilities are established in the directive that accompanies this measure.

== Supervision: Commission for Technology and Digital Innovation (CTID)

The CTID must be part of the governance committees which provide information about decisions that include IT resources and data, in order to facilitate advanced information from resources for programme objectives.
After consultation with other manager’s offices, the CTID can delegate its functions to other technical personnel.

The CTID requires data security and privacy to be completely integrated into the system of data use and evaluation measures at a municipal level, and it can recommend that an organisation’s manager’s office modify, stop or finalise any purchase, investment or activity that includes significant IT components, based on the CTID’s evaluations of the terms of the contracts and current legislation.

A process will be established whereby the CTID will regularly coordinate with project managers in order to evaluate the IT resources and the data-management processes that support the aims and mission of each municipal body.
The CTID and the people responsible for the programme must share the responsibility for ensuring that the IT resources and present and future municipal datasets adequately provide the value they apply to the manager’s offices and municipal bodies.

The manager’s offices and bodies will have to comply with the regulations and instructions for the management of data, information and municipal documents from executive bodies, which will be developed under the Responsible Data-Management Strategy led by the Commission for Technology and Digital Innovation.
